{
  "hash": "789a69e52fc13c7755127de478f9a3a1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simulating spatially varying detectability\"\nauthor: \"Leonard Hambrecht, IRSS, University of British Columbia\"\ndate: \"September 2026\"\nbibliography: references.bib\n---\n\n## Introduction\n\nIn the RMNP survey, animals were harder to detect under dense canopy: the [detection function](detection-function.qmd) with lidar canopy cover (`pabove2`) was clearly better supported than one without it. Detectability therefore varies across the landscape with the forest, and so does the proportion of animals a survey misses.\n\nSimulations normally draw detectability from a fixed detection function, or from individual covariates such as group size that are unrelated to location. The [fork of `dsims`](https://github.com/hambrecht/dsims) adds *spatial* covariates: `make.detectability()` takes a raster through the new `cov.surface` argument, and at every repetition reads the raster at each simulated animal's location. The scale parameter of animal $i$ is then\n\n$$\\log(\\sigma_i) = \\log(\\sigma_0) + \\beta z_i,$$\n\nwhere $z_i$ is the raster value at the animal, $\\beta$ the coefficient given in `cov.param`, and $\\sigma_0$ the scale parameter. This is the same log-linear form that `Distance` uses for covariates, so the fitted coefficients can be used directly. This article is the first documentation of the feature.\n\nThe survey design is fixed throughout: the segmented grid of 10 km north–south transects that is the standard design for aerial ungulate surveys in Alberta (see [*Survey designs with subplots*](simulation-design.qmd#a-segmented-grid-design)). Only detectability and the analysis change. We simulate the moose survey three times: with constant detectability, and with canopy-dependent detectability analysed with and without the canopy covariate. This shows what the covariate changes in the simulated data and whether the analysis has to account for it.\n\n## Prerequisites\n\n`cov.surface` exists only in the fork of `dsims`:\n\n```r\nremotes::install_github(c(\"hambrecht/dssd\", \"hambrecht/dsims\"))\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(here)\nlibrary(dsims)\nlibrary(sf)\nlibrary(terra)\nlibrary(ggplot2)\nstopifnot(\"cov.surface\" %in% names(formals(make.detectability)))\n```\n:::\n\n\nWe load the region, populations and detection function parameters from [*From density surface model to simulation*](simulation-density.qmd), and the segmented grid design from [*Survey designs with subplots*](simulation-design.qmd).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist2env(readRDS(here(\"workflow\", \"outputs\", \"simulation_setup.rds\")), envir = environment())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<environment: R_GlobalEnv>\n```\n\n\n:::\n\n```{.r .cell-code}\ndesign_seg <- readRDS(here(\"workflow\", \"outputs\", \"simulation_designs.rds\"))$design_seg\n```\n:::\n\n\n## The covariate surface\n\n`cov.surface` takes a single-layer raster, read at the animals' `x` and `y` coordinates, so it must be in the same CRS as the region. We write the canopy cover layer to its own GeoTIFF. A file path is better than an in-memory raster for parallel runs, because each worker then reads the file itself instead of receiving a copy of the raster.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlidar <- rast(here(\"data\", \"RMNP\", \"lidar\", \"lidar_pabove2_zmax_10m.tif\"))\nstopifnot(same.crs(lidar, region@region))\ncanopy_file <- here(\"workflow\", \"outputs\", \"pabove2_10m.tif\")\nwriteRaster(lidar[[1]], canopy_file, overwrite = TRUE, names = \"pabove2\")\n```\n:::\n\n\nAnimals outside the raster, here in the part of the park without lidar data, get the raster mean, and `dsims` warns when this happens.\n\n## Detectability that depends on canopy\n\nWe use the fitted hazard-rate detection function for moose: the scale parameter at zero canopy cover, the shape parameter, and the canopy coefficient. The name of the entry in `cov.surface` must match the name in `cov.param`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetect_canopy <- make.detectability(\n  key.function = \"hr\",\n  scale.param = scale_species[[\"Moose\"]],\n  shape.param = shape,\n  cov.param = list(pabove2 = beta_pabove2),\n  cov.surface = list(pabove2 = canopy_file),\n  truncation = TRUNCATION_M\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(detect_canopy, pop_descs$Moose)\n```\n\n::: {.cell-output-display}\n![Moose detection function at the mean canopy cover of the raster (solid), and at the canopy values that bound 95% of the raster (dashed).](simulation-detectability_files/figure-html/fig-detectability-1.png){#fig-detectability width=672}\n:::\n:::\n\n\nThe dashed lines show the range of the covariate effect: detection probability is highest in the open and lowest under the densest canopy. Most of the park lies between these extremes.\n\n## One simulated survey\n\nA single simulated survey shows the covariate at work. The canopy value at each detected group is carried into the survey data, where the analysis can use it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2025)\nsim_one <- make.simulation(reps = 1, design = design_seg, population.description = pop_descs$Moose,\n                           detectability = detect_canopy,\n                           ds.analysis = make.ds.analysis(dfmodel = ~1, key = \"hr\", truncation = TRUNCATION_M))\nsurvey <- run.survey(sim_one)\ndetections <- survey@dist.data[!is.na(survey@dist.data$object), ]\nnrow(detections)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndetections$canopy <- cut(detections$pabove2, c(-Inf, 20, 30, Inf),\n                         labels = c(\"pabove2 < 20%\", \"20-30%\", \"> 30%\"))\nggplot(detections, aes(distance)) +\n  geom_histogram(binwidth = 25, boundary = 0) +\n  facet_wrap(~canopy) +\n  labs(x = \"Distance (m)\", y = \"Detections\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Distances of detected moose groups in one simulated survey, by canopy cover at the group.](simulation-detectability_files/figure-html/fig-one-survey-1.png){#fig-one-survey width=672}\n:::\n:::\n\n\nWith the weak canopy effect estimated from the 10 m lidar, the distance distributions differ only a little between canopy classes.\n\n## Simulations\n\nWe run three simulations of the segmented grid design, each with 100 repetitions:\n\n- **constant**: the constant detection function from [*From density surface model to simulation*](simulation-density.qmd#defining-detectability), analysed without covariates (`~1`). This is the reference.\n- **canopy, `~1`**: canopy-dependent detectability, analysed without covariates. The analysis relies on *pooling robustness*: a detection function without covariates can still estimate density without bias when detectability varies between animals [@buckland2001].\n- **canopy, AIC**: canopy-dependent detectability, with AIC choosing between `~1` and `~pabove2`, as in the real analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_null <- make.ds.analysis(dfmodel = ~1, key = \"hr\", truncation = TRUNCATION_M)\nanalysis_canopy <- make.ds.analysis(dfmodel = list(~1, ~pabove2), key = c(\"hr\", \"hr\"),\n                                    truncation = TRUNCATION_M, criteria = \"AIC\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nREPS <- 100\nset.seed(2025)\nrun <- function(detect, analysis) {\n  sim <- make.simulation(reps = REPS, design = design_seg, population.description = pop_descs$Moose,\n                         detectability = detect, ds.analysis = analysis)\n  run.simulation(sim, run.parallel = TRUE)\n}\nscenarios <- c(\"constant, ~1\", \"canopy, ~1\", \"canopy, AIC\")\nsims <- list(\n  run(detect_constant, analysis_null),\n  run(detect_canopy, analysis_null),\n  run(detect_canopy, analysis_canopy)\n)\nnames(sims) <- scenarios\n```\n:::\n\n\n## Results\n\nFor each simulation we extract the density of individuals (true and mean estimate, animals per km²), the bias, the root mean squared error relative to the true density (RRMSE), the proportion of 95% confidence intervals containing the true density, and the mean coefficient of variation. We also compare the true average detection probability of the groups in the covered area ($P_a$) with its estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_metrics <- function(sim) {\n  s <- summary(sim, description.summary = FALSE)\n  D <- s@individuals$D[nrow(s@individuals$D), ]\n  det <- s@detection\n  data.frame(true_D = D$Truth * 1e6, mean_D = D$mean.Estimate * 1e6,\n             bias_pct = D$percent.bias, rrmse = D$RMSE / D$Truth,\n             ci_coverage = D$CI.coverage.prob, mean_cv = D$mean.se / D$mean.Estimate,\n             true_Pa = det$mean.observed.Pa[nrow(det)], est_Pa = det$mean.estimate.Pa[nrow(det)])\n}\nresults <- cbind(scenario = scenarios, do.call(rbind, lapply(sims, sim_metrics)))\nrownames(results) <- NULL\nknitr::kable(results, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|scenario     | true_D| mean_D| bias_pct| rrmse| ci_coverage| mean_cv| true_Pa| est_Pa|\n|:------------|------:|------:|--------:|-----:|-----------:|-------:|-------:|------:|\n|constant, ~1 |  0.147|  0.147|   -0.120| 0.148|        0.96|   0.157|   0.838|  0.838|\n|canopy, ~1   |  0.147|  0.147|    0.473| 0.160|        0.95|   0.163|   0.826|  0.821|\n|canopy, AIC  |  0.147|  0.154|    4.780| 0.242|        0.95|   0.179|   0.825|  0.815|\n\n\n:::\n:::\n\n\nHow often did AIC choose the canopy model? The `Detection` results record which candidate model was selected in each repetition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected <- sims[[\"canopy, AIC\"]]@results$Detection[1, \"SelectedModel\", seq_len(REPS)]\ncanopy_share <- mean(selected == 2) # model 2 is ~pabove2\ncanopy_share\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.43\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimates <- do.call(rbind, lapply(scenarios, function(sc) {\n  est <- sims[[sc]]@results$individuals$D\n  data.frame(scenario = sc, D = est[dim(est)[1], \"Estimate\", seq_len(REPS)] * 1e6)\n}))\nestimates$scenario <- factor(estimates$scenario, levels = rev(scenarios))\nggplot(estimates, aes(D, scenario)) +\n  geom_boxplot() +\n  geom_point(data = results, aes(true_D, scenario), shape = 124, size = 6, colour = \"red\") +\n  labs(x = \"Estimated density (moose / km²)\", y = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Density estimates across repetitions. The red mark is the true density.](simulation-detectability_files/figure-html/fig-results-1.png){#fig-results width=672}\n:::\n:::\n\n\nWith 100 repetitions, the Monte Carlo standard error of the bias is roughly the RRMSE divided by 10, here one to two percentage points, and that of the confidence interval coverage about 0.02.\n\n- **Detectability.** The fitted canopy effect is weak (a coefficient of -0.0101 per percentage point of `pabove2`). Canopy therefore lowers the average detection probability of moose groups only slightly, from 0.84 to 0.83.\n- **Ignoring canopy.** With canopy-dependent detectability, a detection function without covariates (`~1`) still estimates overall density with a bias of 0.5% and an RRMSE of 0.16, close to the constant-detectability reference (0.148). This is pooling robustness: the detection function averages over the variation in detectability, and because the design samples canopy conditions in proportion to their extent, the average is the right one.\n- **Including canopy.** AIC chose the canopy model in 43% of repetitions. Offering it made the estimates worse rather than better: the RRMSE rose to 0.242 and the bias to 4.8%. With an effect this weak, the extra parameter adds variance, and a hazard-rate model with a covariate is harder to fit reliably to a single survey's data than one without.\n\n## Discussion\n\nFor moose in Riding Mountain National Park, the canopy effect estimated from the 10 m lidar is too weak to matter for the overall density. The simpler analysis without the covariate is both unbiased and more precise. That conclusion depends on the size of the effect. In the RMNP paper, the canopy coefficient was more than twice as strong, and in denser forest the loss of detections under canopy would be larger; rerunning this article with a stronger `cov.param` shows how the conclusions change.\n\nPooling robustness also has limits: it does not protect estimates for parts of the area where detectability differs from the average, such as density in dense forest alone. It also requires the design to sample canopy conditions representatively [@rexstad2023]. A design whose transects under-sample dense forest, or estimates reported by habitat, need the canopy covariate in the analysis. Those are the situations where simulating detectability from the canopy raster is most useful, because constant detectability would hide the problem.\n\nThe [next article](simulation-multispecies.qmd) combines it with species-specific detectability to simulate a multi-species survey.\n\n## Saving\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(results, here(\"workflow\", \"outputs\", \"simulation_detectability.csv\"), row.names = FALSE)\n```\n:::\n\n\n**Next:** [Simulating a multi-species survey](simulation-multispecies.qmd).\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}